### ISSUE TITLE
Create plan for redoing todo-mvp example

### ISSUE THREAD

**Issue by addianto** [addianto/android-architecture#1]
TODO app specifications: https://github.com/googlesamples/android-architecture/wiki/To-do-app-specification

**Comment by addianto** [comment]
I suppose if the app follows certain multi-layered architecture, then each layer can be developed individually, right?

**Comment by addianto** [comment]
I guess the work plan is as follows:

- [ ] Create architectural base classes
- [ ] Create data model
- [ ] Implement local (in-device) persistence model
- [ ] Create packages (folders) representing each use cases
- [ ] Create layouts
- [ ] Integrate data model with the VP (View & Presenter)
